### ISSUE TITLE
Log in via Chrome gets stuck on ORCiD page

### ISSUE THREAD

**Issue by murkatr** [PREreview/prereview#201] opened 2021-02-11 01:13 UTC

**Comment by dasaderi** [comment] 2021-02-11 02:29
I can't reproduce this on my end actually. It seems to work for me.

**Comment by murkatr** [comment] 2021-02-11 16:52
Strange... I'm not sure what to do next, but I definitely cannot log in when using my Chrome browser.

**Comment by harumhelmy** [comment] 2021-02-16 18:52
@murkatr The last time I had this issue, it turned out one of my the browser extensions I installed for privacy was blocking some ORCID cookies. I haven't had the chance to get to to the bottom of which extension was causing that problem though. At any rate, would you mind trying to log in on Chrome incognito (assuming your extensions aren't installed there) and see if that works?

**Comment by harumhelmy** [comment] 2021-02-16 19:33
Actually, this just started happening to me when I tried logging in to the production site, UGH! And I see on Slack that a mentee is having the same issues. Will make this priority.

**Comment by harumhelmy** [comment] 2021-02-17 15:16
per @georgiamoon this is also happening on her Firefox! I've personally only been able to reproduce on Chrome

**Comment by jheretic** [comment] 2021-02-17 15:53
@georgiamoon are you getting a CORS error in your console when you are having login problems? That's one possible cause we're trying to track down.

@harumhelmy I don't know if this would be helpful, but we could potentially switch up the whole way we're tracking sessions by leveraging `koa-session`'s support for session tracking via a data store like postgres or redis rather than via cookies. Just as a potential nuclear option.

**Comment by georgiamoon** [comment] 2021-02-18 00:11
This is the error I'm seeing, which doesn't seem to illuminate anything that makes sense?
<img width="1132" alt="Screen Shot 2021-02-17 at 7 10 19 PM" src="https://user-images.githubusercontent.com/941210/108284784-deda3a00-7153-11eb-8682-7c90d1b79a4e.png">

**Comment by jheretic** [comment] 2021-02-23 14:59
@georgiamoon Yeah that shouldn't have anything to do with it. Also the CORS error I mentioned would only show up on prereview.org pages of the login workflow, not on ORCiD.

**Comment by murkatr** [comment] 2021-02-24 06:05
**A review of what was mentioned in our call today:**
- When Trusted Organizations was cleared, I was able to re-authorize via Safari & Firefox, but not Chrome
- After going to https://outbreaksci.prereview.org/ (which now looks like https://prereview.org/communities/outbreaksci), and logging in there while using Chrome - I was able to get into prereview.org instead of being stuck on the orcid.org page!!

**Comment by jheretic** [comment] 2021-03-26 17:56
This seems to be fixed now.

**Closed by jheretic** 2021-03-26 17:56 UTC
Labels: bug
