### ISSUE TITLE
When in read review mode avatar menu shows "Complete profile" notification - broken link

### ISSUE THREAD

**Issue by dasaderi** [PREreview/prereview#295] opened 2021-03-31 19:24 UTC
When in read review mode the avatar shows a red notification (probably inherited from OSrPRE) and the menu seems to be the old one with Complete profile. But when clicking on that it brings to a broken Not Found page as shown below.

![Screen Shot 2021-03-31 at 12 22 10 PM](https://user-images.githubusercontent.com/13750121/113199416-f65d1600-921b-11eb-9593-f865f4275b42.png)
![Screen Shot 2021-03-31 at 12 22 21 PM](https://user-images.githubusercontent.com/13750121/113199428-f8bf7000-921b-11eb-9541-a78569b96a96.png)

**Comment by harumhelmy** [comment] 2021-04-01 16:58
This is a duplicate of #195, closing this one.

**Closed by harumhelmy** 2021-04-01 16:58 UTC
Labels: bug, profile
