### ISSUE TITLE
Licensed under CC-BY 4.0

### ISSUE THREAD

**Issue by murkatr** [PREreview/prereview#112] opened 2021-01-13 18:11 UTC
When you submit DOI, the review will be licensed under CC-BY 4.0 and PREreview will then add "CC-BY 4.0" under reviews.

**Comment by dasaderi** [comment] 2021-02-10 21:09
Licence: https://creativecommons.org/licenses/by/4.0/

We can add the tag https://creativecommons.org/choose/results-one?license_code=by&amp;jurisdiction=&amp;version=4.0&amp;lang=en and link to the link above.

**Comment by jheretic** [comment] 2021-02-16 21:07
Duplicate of #1

**Closed by jheretic** 2021-02-16 21:07 UTC
Labels: frontend
